FROM python:3

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        sshpass \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /ansible-conda
ADD . .
RUN pip --disable-pip-version-check install -r tests/integration/runner-requirements.txt

WORKDIR /ansible-conda/tests/integration
ENV ANSIBLE_HOST_KEY_CHECKING=False
#CMD ["ansible-playbook", "-i", "inventory.ini", "-vvv", "test.yml"]

CMD "sh -c 'ssh -o StrictHostKeyChecking=no root@ansible-conda-integration-conda-py2-4-4-10-test-instance'"